### ISSUE TITLE
Automate ioos by the numbers generation

### ISSUE THREAD

**Issue by MathewBiddle** [MathewBiddle/ioos_by_the_numbers#2]
Currently the [IOOS by the numbers metrics](https://github.com/MathewBiddle/ioos_by_the_numbers/blob/main/ioos_btn_metrics.csv) are collected on a manual basis by running the [Jupyter Notebook](https://github.com/MathewBiddle/ioos_by_the_numbers/blob/main/IOOS_BTN.ipynb). The process should be automatically ran, using GH-Actions similar to the GTS metrics, on an annual? quarterly? basis.

**Comment by MathewBiddle** [comment]
Steps:

- [ ] Translate notebook to python script
- [ ] determine frequency
- [ ] build GitHub Action

**Comment by MathewBiddle** [comment]
@ocefpaf do you have an example of running a jupyter notebook in a GitHub Action?

**Comment by ocefpaf** [comment]
> @ocefpaf do you have an example of running a jupyter notebook in a GitHub Action?

There are many ways to do that but I [prefer a single call to nbconvert](https://github.com/ocefpaf/glideroftheday/blob/main/.github/workflows/tweet_map.yaml#L38). I usually save the notebook without any output and "convert" it to a notebook with the outputs.

**Comment by MathewBiddle** [comment]
I'd like to follow the single call to nbconvert to run the notebook and be done. Remove the standalone python script. Here's the addition to run the notebook.

```
      - name: Setup Conda
        uses: s-weigand/setup-conda@v1
        with:
          activate-conda: false
          conda-channels: conda-forge
      - name: Build environment
        shell: bash -l {0}
        run: |
          conda env create -f environment.yml
      - name: Execute Notebook
        run: |
          source activate ioos-btn
          jupyter nbconvert --to notebook --execute IOOS_BTN.ipynb --output=IOOS_BTN.ipynb
```
